import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-elevated": "#1a1a1d",
        "border-hover": "rgba(255, 255, 255, 0.12)",
        "on-background": "#e5e1e4",
        "primary-container": "#7c3aed",
        "primary-fixed": "#eaddff",
        "inverse-on-surface": "#313032",
        "on-primary-fixed-variant": "#5a00c6",
        "bg-overlay": "rgba(9, 9, 11, 0.85)",
        "tertiary-container": "#a15100",
        "tertiary-fixed-dim": "#ffb784",
        "primary": "#d2bbff",
        "surface-container": "#201f22",
        "surface-container-high": "#2a2a2c",
        "text-secondary": "#a1a1aa",
        "border-whisper": "rgba(255, 255, 255, 0.06)",
        "accent-glow": "rgba(124, 58, 237, 0.20)",
        "background": "#131315",
        "secondary-fixed-dim": "#cebdff",
        "danger": "#ef4444",
        "on-tertiary-fixed-variant": "#713700",
        "tertiary": "#ffb784",
        "surface-container-highest": "#353437",
        "inverse-primary": "#732ee4",
        "on-tertiary-container": "#ffe0cd",
        "error-container": "#93000a",
        "surface": "#131315",
        "bg-surface": "#111113",
        "on-secondary-fixed-variant": "#4f319c",
        "secondary": "#cebdff",
        "secondary-container": "#4f319c",
        "on-surface-variant": "#ccc3d8",
        "error": "#ffb4ab",
        "on-secondary": "#381385",
        "inverse-surface": "#e5e1e4",
        "on-error-container": "#ffdad6",
        "surface-dim": "#131315",
        "on-primary-fixed": "#25005a",
        "on-secondary-container": "#bea8ff",
        "on-primary-container": "#ede0ff",
        "on-tertiary-fixed": "#301400",
        "on-primary": "#3f008e",
        "outline": "#958da1",
        "surface-variant": "#353437",
        "outline-variant": "#4a4455",
        "on-error": "#690005",
        "on-secondary-fixed": "#21005e",
        "surface-tint": "#d2bbff",
        "on-tertiary": "#4f2500",
        "accent-bg": "rgba(124, 58, 237, 0.08)",
        "surface-bright": "#39393b",
        "tertiary-fixed": "#ffdcc6",
        "text-muted": "#7d7d87",
        "text-primary": "#fafafa",
        "success": "#22c55e",
        "on-surface": "#e5e1e4",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1c1b1d",
        "secondary-fixed": "#e8ddff",
        "primary-fixed-dim": "#d2bbff",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        md: "16px",
        "grid-base": "4px",
        xl: "32px",
        sm: "8px",
        xs: "4px",
        "max-width": "1200px",
        "2xl": "48px",
        "3xl": "64px",
        "4xl": "96px",
      },
      fontFamily: {
        "card-title": ["Geist", "sans-serif"],
        "label-mono": ["Geist Mono", "monospace"],
        "hero-heading": ["Geist", "sans-serif"],
        "hero-heading-mobile": ["Geist", "sans-serif"],
        "stat-display": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-main": ["Inter", "sans-serif"],
        "section-heading": ["Geist", "sans-serif"],
      },
      fontSize: {
        "hero-heading": ["80px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "hero-heading-mobile": ["48px", { lineHeight: "1.1", fontWeight: "700" }],
        "section-heading": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "card-title": ["18px", { lineHeight: "1.4", fontWeight: "500" }],
        "stat-display": ["48px", { lineHeight: "1", fontWeight: "700" }],
        "body-lg": ["24px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-main": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "label-mono": ["11.5px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    require('tailwindcss-animate')
  ],
};

export default config;
